### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(PanCrack)
add_subdirectory(PanCrackContent)
add_subdirectory(App)


target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    PanCrackplugin
    PanCrackContentplugin)

